runtime: php55
api_version: 1

handlers:
  - url: /(.+\.php)$
    script: \1

  - url: /*
    script: login.php

  - url: /(.+\.(gif|png|jpg))$
    static_files: \1
    upload: .+\.(gif|png|jpg)$
    application_readable: true
